{{- if and .Values.rgw.credentials.create (not .Values.rgw.credentials.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "extended-ceph-exporter.credentialsSecretName" . }}
  labels:
    {{- include "extended-ceph-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.rgw.credentials.accessKeyKey }}: {{ .Values.rgw.credentials.accessKey | quote }}
  {{ .Values.rgw.credentials.secretKeyKey }}: {{ .Values.rgw.credentials.secretKey | quote }}
{{- end }}
