{
 "title": "Extended Ceph Exporter RGW Overview",
 "tags": [
  "ceph",
  "rook",
  "rgw",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "topBuckets", "label": "Top Buckets", "query": "5,10,20,50,100" },
   {
    "name": "realm",
    "label": "Realm",
    "query": {
     "query": "label_values(extended_ceph_rgw_bucket_info, realm)"
    }
   },
   {
    "name": "store",
    "label": "Store",
    "query": {
     "query": "label_values(extended_ceph_rgw_bucket_info, store)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Bucket Size Over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(max by (bucket, realm, store, tenant, user) (extended_ceph_rgw_bucket_usage_bytes{realm=~\"$realm\",store=~\"$store\"}))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Top $topBuckets Buckets by Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk($topBuckets, max by (bucket, realm, store, tenant, user) (extended_ceph_rgw_bucket_usage_bytes{realm=~\"$realm\",store=~\"$store\"}))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Total Bucket Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (bucket, realm, store, tenant, user) (extended_ceph_rgw_bucket_usage_bytes))"
    }
   ]
  },
  {
   "title": "Total Objects",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (bucket, realm, store, tenant, user) (extended_ceph_rgw_bucket_objects))"
    }
   ]
  },
  {
   "title": "Bucket Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max by (bucket, realm, store, tenant, user) (extended_ceph_rgw_bucket_info))"
    }
   ]
  },
  {
   "title": "User Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max by (realm, store, tenant, user) (extended_ceph_rgw_user_info))"
    }
   ]
  },
  {
   "title": "Buckets by Size",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sort_desc(max by (bucket, tenant) (last_over_time(extended_ceph_rgw_bucket_usage_bytes{realm=~\"$realm\",store=~\"$store\"}[$__range])))"
    },
    {
     "expr": "max by (bucket, tenant) (last_over_time(extended_ceph_rgw_bucket_objects{realm=~\"$realm\",store=~\"$store\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Users by Size",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sort_desc(max by (tenant, user) (last_over_time(extended_ceph_rgw_user_usage_bytes{realm=~\"$realm\",store=~\"$store\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Bucket Quota Max Size",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sort_desc(max by (bucket, realm, store, tenant, user) (extended_ceph_rgw_bucket_quota_max_size_bytes{realm=~\"$realm\",store=~\"$store\"}))"
    }
   ]
  },
  {
   "title": "User Quota Max Size",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sort_desc(max by (realm, store, tenant, user) (extended_ceph_rgw_user_quota_max_size_bytes{realm=~\"$realm\",store=~\"$store\"}))"
    }
   ]
  }
 ]
}